### ISSUE TITLE
IE8 Support

### ISSUE THREAD

**Issue by benjamincharity** [Venturocket/angular-slider#15]
I was just wondering what the issues with older IE are. This slider looks great but as I am stuck with IE8 currently I was curious as to what issues I might face if I was to look at adding support.

Thanks

**Comment by henrahmagix** [comment]
I too would love to know this =)

**Comment by drgould** [comment]
Well, the biggest issue I've run into is the angular core simply not working in IE8 at all. Also, the angular team has deprecated IE8- support from v1.2+, so I wouldn't hold out much hope of it working with a relatively new-ish version of angular. Other than that, I haven't looked too much into it since we haven't supported IE8 for any of the projects that use this for quite some time.

Keep me updated if you do end up undertaking such a project, there aren't many good active options for older browsers currently.

**Comment by henrahmagix** [comment]
I just tested in IE8 and it works fine.

@drgould Your angular core problem is with v1.3+, not v1.2 which supports IE8 fine. I'm running v1.2.13. (See http://blog.angularjs.org/2013/12/angularjs-13-new-release-approaches.html)

**Comment by drgould** [comment]
Ah yes, @henrahmagix you're right. I guess I've just been reading too much about v2.0 that I forgot they haven't deprecated IE8 yet.
