### ISSUE TITLE
Setting 'floor' and 'ceiling' with data-bind

### ISSUE THREAD

**Issue by bertop89** [Venturocket/angular-slider#18]
Unlike 'ng-model', 'floor' and 'ceiling' cannot be initialized from javascript code. Is it not implemented or am I doing something wrong?

**Comment by henrahmagix** [comment]
There are many attributes that don't get parsed as an angular expression: `floor` and `ceiling` are such attributes. The others can be [seen here](https://github.com/Venturocket/angular-slider/blob/1aea84ef9b0f30eaca181b408b081784b26059ac/src/angular-slider.js#L219-L225).

Not being parsed as an angular expression means you need to use `{{ }}` to get the value from an angular variable, like so: 

``` html
<slider ng-model="sliderModel" floor="{{ floorValue }}" ceiling="100">
```

where `sliderModel` and `floorValue` are angular variables, and `100` is a string representing an integer.

**Comment by bertop89** [comment]
Thanks for the quick response! That was what I was trying but it was not working. Found out it was a conflict with the twig templating syntax which uses the brackets also for its controllers.

Just out of curiosity, how do you guys decide which attributes get parsed as an angular expression and which not?

**Comment by henrahmagix** [comment]
When setting up the attributes one wants from a directive, they can be set to `=` (angular parsing), `@` (no parsing), or `&` (use parent scope). This is decided on the directive.

Often you will get parsing errors when trying to pass a value of `100` to an `=` attribute, which is why this library is setup to allow values to be placed straight into the config attributes: so you can write `floor="0" ceiling="100"` without having to resort to setting variables on the scope.

**Comment by bertop89** [comment]
I see, thank you again for your thorough explanation!

**Comment by henrahmagix** [comment]
You're welcome =)

**Comment by renanlecaro** [comment]
I was having the same problem, maybe that's worth putting in the readme file ?
Thanks a lot for this module anyway, it's extremely usefull for our class projet :)

**Comment by drgould** [comment]
Yeah, I'll try to make it more explicit in the readme.
