### ISSUE TITLE
Multiple Directive Resource Contention Error

### ISSUE THREAD

**Issue by mdedetrich** [Venturocket/angular-slider#24]
Getting the following error when using the `step` option for a slider

http://docs.angularjs.org/error/$compile/multidir?p0=slider&p1=step&p2=new

``` html
<slider floor="100" ceiling="10000" precision="2" ng-model="item.cost" step="100"></slider>
```

Using AngularJS version 1.2.16

**Comment by drgould** [comment]
I'm not getting this error. Do you have another directive in your scope named `step`? That's what that error seems to be saying. If so, is it widely used? (i.e. should I make the slider account for the collision?)

**Comment by mdedetrich** [comment]
I am having issues actually diagnosing this problem, I was on the angularJS IRC channel, and they implied it was an issue with the library (I suspected otherwise)

The thing is, my project is definitely a non trivial size right now, and I have no idea how to debug the current directives in scope (and more importantly, which AngularJS module they come from)

Any idea on how to do this?

Probably the ideal way is to make it account for collision. This error is unique to `AngularJS` 1.2.0, it happens when two directives try and do a specific operation that creates a collision

**Comment by drgould** [comment]
Which version of the slider are you using?

**Comment by mdedetrich** [comment]
0.2.5, tried to use 0.3.0 yesterday but the bower build was broken (it didn't contain any JS files). Should I try with 0.3.1 (which just got released yesterday?)

**Comment by drgould** [comment]
Yeah. I don't really think it'll fix it but at least you'll be on the newest version. Also note the breaking changes in the release notes when you change over. 

As for trying to find the offending module: the first thing I'd do is search through your project for `directive('step'` and `directive("step"`.

**Comment by mdedetrich** [comment]
This is the library where the collision comes from https://github.com/madmimi/angular-foundation. If you go to http://madmimi.github.io/angular-foundation/ and mm-foundation-tour, you will see the step directive they have defined.

Updating to latest version now, will let you know how it goes

**Comment by mdedetrich** [comment]
Upgrading to `0.3.1` unsurprisingly made no difference

**Comment by drgould** [comment]
Ugh, I feel like this is their fault for using such a generic directive name (especially considering `step` is a native attribute on `input` tags). Maybe you can petition them to change the name to `tour-step` or something similar for that reason.

Are you using that part of their library? If not, try picking and choosing the directives you actually use rather than throwing it all in. I've been burned many times before by blanket including modules. If not, I can add in `step-width` as an alias to `step` so you can use the slider in the meantime.

**Comment by mdedetrich** [comment]
Just had a discussion on freenode, their comment is that directives should always be namespaced (and apparently they have been nagging the community consistently to do this). Actual directives should definitely be namespaced, which means that ideally foundation should namespace their library

**Comment by ProLoser** [comment]
@drgould both projects should be using prefixes.

**Comment by drgould** [comment]
@ProLoser generally I agree, but I feel it's only necessary for directive names. Personally I find it incredibly annoying when I use directives that prefix all their attributes as well (`vr-floor`, `vr-ceiling`, `vr-step`, etc...ugh). It's highly (highly!) unlikely that multiple directives with alike attributes will be used on a single element, so prefixing the attributes is an unnecessary extra step and only degrades the readability and write-ability IMHO.

**Comment by ProLoser** [comment]
Unfortunately there is no distinction to angular between options and directives. So as much as I agree with the "it's verbose/annoying" there really isn't much we can do about it.

This is why we use `ui-options` instead of just `options` in angular-ui.

FYI: I hate when directives abuse using a plethora of options as specific attributes (more than 2 or 3 usually) because it makes the HTML just as verbose and tedious. This is why we try to introduce global configurations and generally lump large collections of options together.

**Comment by mdedetrich** [comment]
For now, is it possible to just alias the `step` directive as suggested?

**Comment by drgould** [comment]
@ProLoser You're right, the number of attributes has gotten a little out of hand. I'll break out all the options into a single attribute in the next milestone.

@mdedetrich Sure, I'll let you know when it's done.

**Comment by ProLoser** [comment]
@drgould in retrospect this is essentially the same as `<input type="range">`. In which case I think your attributes might be acceptable (although I find it a little silly you don't simply emulate the `type=range` api for simplicity). Essentially a non-jquery version of https://github.com/angular-ui/ui-slider

The only reason why I would probably let this sort of thing slide is because we're actually deliberately emulating the native API and benefitting from it. By using an input tag and native properties we're gaining validation as well as configuration options.

However, it may still be beneficial to ALSO provide a simple vr-options so if someone wants to pass the entire configuration in 1 property. I would also suggest using a global config so that people don't have to configure each and every instance on the page. Not that either of these theoretically solve the problem.

But there's also this too: https://github.com/madmimi/angular-foundation/issues/14

**Comment by mdedetrich** [comment]
In the case of slider, global config's may not be the best solution because sliders typically have a lot of configurable options per instance.

The solution to allow you to provide an object as an option is probably the best solution, its how a lot of directives handle it when they deal with an excessive amount of options

**Comment by drgould** [comment]
@mdedetrich v0.3.2 has the change.
